name: CMake Build on AArch64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU for AArch64
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies for AArch64
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Configure CMake for AArch64
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_SYSTEM_NAME=Linux \
                -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
                -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
                -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ ..

      - name: Build with CMake
        run: |
          cd build
          make

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Package the build
        run: |
          cd build
          cpack

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: build/
